INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac2003', 'soil science', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac2003-01', 'soil science', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac3002', 'soil chemistry', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac3009', 'environmental microbiology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac3035', 'plant nutrition', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac3037', 'molecular biology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac5041', 'agricultural pesticides', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac5044', 'soil chemical analysis', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac5063', 'introduction to plant biotechnology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac5066', 'molecular recognition', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac5095', 'theory and application of anaerobes and extremoph', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac5100', 'special topics in environmental microbiology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ac5102', 'application of bioinformatics in microbiology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron1005', 'introduction to crop production', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron1008', 'introduction to crop science', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron1009', 'introduction to crop science', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron2001', 'genetics', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron2002', 'statistics', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron2013', 'experimental design', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron3001', 'field crops', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron3005', 'plant breeding', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron4001', 'crop physiology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron4003', 'tea cultivation science', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron4023', 'applied linear algebra', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5001', 'advanced genetics', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5002', 'method of advanced biometrics (1)', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5003', 'method of advanced biometrics (2)', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5019', 'plant molecular breeding', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5022', 'statistical consulting', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5028', 'plant cell and tissue culture', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5046', 'statistical computations and analysis', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5049', 'statistical analysis for genomic data', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5050', 'introduction to bioinformatics', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5059', 'applied multivariate statistical methods', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5074', 'statistical methods for agronomists', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5077', 'design and analysis of factorial experiments', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5079', 'weed management', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5091', 'crop-insect interactions', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5093', 'crop modeling', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5096', 'categorical data analysis', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5097', 'statistical learning', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5099', 'trends in agronomy', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5101', 'image analysis in crop life cycle', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron5106', 'computational skills for biological data analysis', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron7002', 'seminar', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('agron7024', 'linear models', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('aia5350', 'deep learning', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('am7144', 'special topics on biomedical engineering', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('asphys7016', 'advanced astronomical observation', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('atgs7230', 'data analysis applications in agricultural sciences', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ba4009', 'data visualization with modern data science', 107);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bchem5055', 'principles of biochemical techniques and data analysis', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bme7402', 'random signal analysis', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bme7417', 'probabilistic generative models', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bse2029', 'ecology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bse5064', 'soil and water conservation engineering', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bse5114', 'artificial neural networks g theory and application', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bse5181', 'water quality protection and watershed management', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bse7032', 'agriculture and environment', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bst5041', 'fundamentals and frontiers of biotechnology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bst5042', 'fundamentals and frontiers of biotechnology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('bst5043', 'fundamentals and frontiers of biotechnology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cba5001', 'agriculture of taiwan', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cba5059', 'introduction of intelligent agriculture', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chem1009', 'general chemistry', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chem1010', 'general chemistry laboratory', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chem2020', 'organic chemistry', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chem2040', 'analytical chemistry', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chem5056', 'bio-analytical chemistry', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chem5071', 'special topics on organic spectroscopy', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chin1036', 'empirse in literature', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('chin1103', 'chinese classics and modern civilization', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cie1013', 'applied mechanics', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cie5141', 'computer vision in construction', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cie5149', 'reliability and risk assessment', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cie5151', 'deep learning in computer vision', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('clinmd5015', 'python for biologists', 104);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cls2001', 'programming skills for life science', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('cls5004', 'academic english writing', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('comme5071', 'biomedical imaging', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie1212', 'data structures and algorithms', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie3005', 'foundations of artificial intelligence', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5002', 'prediction, learning, and games', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5036', 'bioinformatics', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5043', 'machine learning', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5210', 'web programming and applications', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5310', 'virtual machines', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5375', 'design for smart sensing systems', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5410', 'optimization algorithms', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5421', 'embodied vision', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5439', 'deep reinforcement learning', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie5452', 'introduction to intelligent vehicles', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie7210', 'parallel and distributed programming', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie7411', 'generative artificial intelligence safety', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie7434', 'brain theory', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('csie7644', 'advanced human computer interaction', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('data5006', 'computer programming in python', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('econ1022', 'principle of microeconomics', 103);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ee4032', 'semiconductor engineering', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ee5149', 'biological physics', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ee5183', 'financial technology', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ee5184', 'machine learning', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ee7012', 'genechips methods and data analysis', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5045', 'population genetics', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5054', 'intertidal ecology:a field study approach', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5087', 'molecular evolution: principles and practice', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5091', 'biological scientific illustration', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5094', 'python for biologist', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5096', 'introduction to theoretical ecology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5104', 'network ecology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5105', 'evolutionary thinking', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5106', 'evolutionary thinking', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eeb5107', 'evolutionary thinking', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ent5069', 'edible insects', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('enve7102', 'air quality management', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('eohs7015', 'risk assessment', 108);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('epm5044', 'modeling of infectious diseases epidemiology', 108);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('epm8090', 'applied stochastic process', 108);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fin1009', 'personal finance planning', 107);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fin7027', 'futures and options markets', 107);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fin7050', 'stochastic process', 107);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fin7065', 'interest rate derivatives markets', 107);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fishsc5077', 'seminar on quantitative ecology and fisheries resource', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fl1003', 'freshman english(i)', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fl1007', 'english', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fl2169', 'czech(i)(1)', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('fl4144', 'spanish(iii)(2)', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('forest5035', 'exploring taiwan: natural environment and resources', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('forest5071', 'exploring taiwan: natural resources conservation and management', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('genedu5022', 'get ready for your career', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('genedu5030', 'introduction to data science', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('gensys5004', 'genome and systems biology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('gensys5020', 'bioinformatics', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('geog1025', 'introduction to human geography', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('geog2015', 'culture, society, and nature', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('geog2017', 'spatial analysis', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('h0113300', 'semiconductor processes and technologies', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('h0113600', 'introduction to semiconductor intelligent manufacturing', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('his3099', 'history of japan feudalism period', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('hist1591', 'china in modern timesg1911-1979', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('hist1594', 'the history and culture of taiwan', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('hist1621', 'ancient chinese intellectual history', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('hort1014', 'pomology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('hort3002', 'plant propagation', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('hort5045', 'orchid physiology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ie5032', 'introduction to stochastic modeling', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ie504', 'production and operations scheduling', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ie5054', 'data analytics', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ie5059', 'engineering statistics', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ie5064', 'intelligent manufacturing systems and management', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('iet1001', 'introduction to engineering', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('im1013', 'statisticsdata analysis and machine learning with python', 107);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('imps1004', 'artificial intelligence programming with python - for beginners', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('imps1005', 'doe for interdisciplinary learners', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('imps1006', 'doe for interdisciplinary learners', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('imps1007', 'doe for interdisciplinary learners', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('imps5012', 'introduction to interdisciplinary statistical data analysis', 116);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('jpnl1002', 'japanese(2)', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('jpnl2018', 'japanese i(spring)', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('jpnl4030', 'japanese (2)', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('law4270', 'medical law and liability', 110);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls1011', 'general botany', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls1011-01', 'general botany', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls3016', 'plant physiology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls5049', 'rna biology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls5073', 'mathematics for life', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls5075', 'bioinformatics', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls5085', 'synthetic biology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ls5118', 'r programming for biology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('math4006', 'calculus (1)', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('md&ph5001', 'health care', 104);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('me2001', 'engineering mathematics(1)', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('me2002', 'engineering mathematics(2)', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('me2006', 'mechanism', 105);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('mgt2002', 'statistics', 107);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ntldev1098', 'eu jean monnet chairxintroduction to mainland china study', 103);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ocean5052', 'computer intensive statistics in ecology', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ocean5067', 'special topics on ichthyology', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ocean5105', 'population ecology and sustainable fisheries resources', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ocean5160', 'macroecology and pattern analysis', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ph2022', 'epidemiology', 108);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('pharm7032', 'pharmaceutical technology', 104);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('phl1511', 'logic', 101);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm2001', 'mycology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm2005', 'methods in plant pathology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm3009', 'plant virology and lab', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm3013', 'plant pathology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm3017', 'molecular biology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm5001', 'cell biology', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm5007', 'disease of fruits trees', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm5013', 'plant disease and diagnosis', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm5075', 'fungal taxonomy, phylogeny, and evolution', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ppm5084', 'applied biostatistics', 106);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('prog5145', 'molecular biology', 111);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ps4512', 'introduction to the history of statistics', 103);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('ps5066', 'seminar on east asia', 103);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('psy1006', 'mind and brain', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('psy1007', 'general psychology', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('random39624', 'introduction to scientific computing and artificial intelligence platform', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('random41585', 'data analytics', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('random87785', 'production and operation scheduling', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('random94389', 'air quality management', 109);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('soc1027', 'introductory sociology', 103);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5004', 'theory of statistics (1)', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5005', 'theory of statistics', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5006', 'regression analysis', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5008', 'multivariate statistical analysis', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5009', 'statistical learning', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat501', 'statistical deep learning', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5011', 'statistical deep learning', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5013', 'time series analysis', 102);
INSERT INTO CourseCatalog (CourseNumber, CourseName, CollegeId) VALUES ('stat5015', 'lifetime data analysis', 102);
